### ISSUE TITLE
TypeError: zodSchema.openapi is not a function

### ISSUE THREAD

**Issue by perry-mitchell** [asteasolutions/zod-to-openapi#21]
Hi,

I'm getting the following error when using the `.openapi()` method:

```
TypeError: zodSchema.openapi is not a function
    at OpenAPIRegistry.register (/data/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-registry.js:19:46)
    at file:///data/dist/schemas/request/lead.js:5:39
```

I'm just using it like so:

```typescript
    registry.registerPath({
        method: "get",
        path: "/api/v1/lead/:id",
        description: "Get a Lead by its ID",
        summary: "Get a single Lead",
        request: {
            params: LeadGetSchema.strip().openapi({ description: "Lead parameters" })
        },
        responses: {
            200: {
                mediaType: "application/json",
                schema: z.object({
                    lead: LeadSchema.openapi({ description: "Resulting Lead object" })
                })
            },
            404: {
                mediaType: "text/plain",
                description: "Lead not found",
                schema: z.void()
            }
        }
    });
```

And that `LeadGetSchema` is as follows:

```typescript
export const LeadGetSchema = REGISTRY.register(
    "Lead GET parameters",
    z
        .object({
            id: z.string().min(1).regex(ID_NUMBER_REXP)
        })
        .strict()
);
```

I'm not sure what I'm doing wrong..

**Comment by perry-mitchell** [comment]
Nevermind, I hadn't called `extendZodWithOpenApi` early enough.
